version: '3'
services:
  ide:
    build:
      context: .
      dockerfile: Dockerfile-ide 
    image: theiaide/theia:latest
    user: ${uid}
    volumes: 
      - ./functions:/home/project
  lb:
    image: nginx:alpine
    links:
      - ide
      - functions
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - '${PORT:-80}:80'
  functions:
    build: .
    environment:
      BOX_CONFIG_FILE: ./config/44168077_i6b5nddq_config.json
    volumes:
      - .:/usr/src/app